config/routes.rb
RailsForZombies::Application.routes.draw do
  root to: "tweets#index"
  resources :tweets
  resources :zombies
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :status, :zombie_id
  validates :status, presence: true, length: { maximum: 140 }
  validates :zombie_id, presence: true
  belongs_to :zombie
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def create
    @tweet = Tweet.new(params[:tweet])
    
    if @tweet.save
      flash[:notice] = "New tweet added!"
      redirect_to root_path
    else
      flash[:notice] = "There was a problem"
      render "new"
    end
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update_attributes(params[:tweet])
    if @task.save
      flash[:notice] = "Tweet Updated!"
      redirect_to tweets_path
    else
      flash[:notice] = "There was a problem:"
      render "edit"
    end
  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  
  def show
    @zombie = Zombie.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsForZombies</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice].present? %>
		<p style="color: white; background: green; padding: 6px"><%= flash[:notice] %></p>
	<% end %>
	
	<%= link_to image_tag("twitter.png", size: '300x200'), "http://localhost:3000" %>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>List of Tweets</h1>

<table>
	<tr>
		<th>Status</th>
		<th>Zombie</th>
	</tr>
	
	<% @tweets.each do |tweet| %>
		<tr>
			<td><%= tweet.status %></td>
			<td><%= link_to tweet.zombie.name, tweet.zombie %></td>
			<td><%= link_to "Edit", edit_tweet_path(tweet.zombie) %></td>
			<td><%= link_to "Delete", tweet, confirm: "Are you sure?", method: 'delete' %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Compose new Tweet", new_tweet_path %>			

app/views/tweets/new.html.erb
<h1>Compose a new tweet</h1>

<%= form_for @tweet do |f| %>

<p>  
  <%= f.label :status %>
  <%= f.text_field :status %>
</p>  

<p>  
  <%= f.label "Zombie ID" %>
  <%= f.text_field :zombie_id %>
</p>

  <%= f.submit %>
  
<% end %>

app/views/tweets/show.html.erb
<h1><%= @tweet.status %></h1>

<p>Posted by <%= @tweet.zombie.name %></p>

app/views/zombies/index.html.erb
<h1>List of Zombies</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Last Tweet</th>
	</tr>

<% Zombie.all.each do |zombie| %>
	<tr>
		<td><%= link_to zombie.name, zombie %></td>
		<td><%= zombie.tweets.last.status %></td>
	</tr>
<% end %>	

app/views/zombies/show.html.erb
<h1>Profile for Zombie <%= @zombie.name %></h1>

	<table>
		<tr>
			<th>Status</th>
			<th>Date Added</th>
		</tr>

		<% @zombie.tweets.each do |tweet| %>
		<tr>
			<td><%= tweet.status %></td>
			<td><%= tweet.created_at %></td>
			<% end %>
		</tr>
	</table>		